import asyncio
import logging
from typing import Any, Dict, List
from app.database.connection import get_database

logger = logging.getLogger("jalrakshak.seed")

# =====================================================================
# 1. SEED CITIES DATA
# =====================================================================
CITIES_DATA: List[Dict[str, Any]] = [
    {
        "id": "mumbai",
        "name": "Mumbai",
        "state": "Maharashtra",
        "region": "West Coast",
        "center": [19.0760, 72.8777],
        "coordinates": {"x": 28, "y": 55},
        "floodRisk": "CRITICAL",
        "riskColor": "#ff334b",
        "rainfall": 68.0,
        "rainfallStr": "68.0 mm/hr",
        "activeAlerts": 12,
        "affectedZones": 18,
        "infrastructureRisk": 7,
        "readiness": 82,
        "inundation": 1.45,
        "waterloggingSeverity": "EXTREME (River Overflow & Tidal Surcharge)",
        "trend": "Surging (+14 mm/hr expected)",
        "floodProneZones": [
            "Kurla West & Mithi River Basin",
            "Hindmata Lowland Depression",
            "Milan Subway Corridor",
            "Sion Circle & Gandhi Market",
            "Andheri Subway & Sahar"
        ],
        "roadsAffected": 24,
        "hospitalsAtRisk": 4,
        "transportImpact": "Central & Harbour local train slow corridors restricted; 3 subways barricaded",
        "powerRisk": "Kurla 33kV Substation on auxiliary GenSet backup",
        "shelters": 42,
        "sheltersActive": 16,
        "emergencyVehicles": 84,
        "responseTeams": 18,
        "criticalWarnings": "High Tide Surge of 4.54m at 14:45 IST coinciding with convective cloudburst.",
        "riverCatchment": "Mithi River & Mahim Creek Estuary",
        "explanation": "Elevated flood exposure is concentrated across low-lying western and eastern suburbs, with intense rainfall increasing waterlogging risk around major drainage corridors and tidal outfall chokepoints."
    },
    {
        "id": "delhi",
        "name": "Delhi",
        "state": "Delhi NCR",
        "region": "North",
        "center": [28.6139, 77.2090],
        "coordinates": {"x": 36, "y": 28},
        "floodRisk": "HIGH",
        "riskColor": "#ff7700",
        "rainfall": 52.0,
        "rainfallStr": "52.0 mm/hr",
        "activeAlerts": 8,
        "affectedZones": 12,
        "infrastructureRisk": 5,
        "readiness": 76,
        "inundation": 0.95,
        "waterloggingSeverity": "HIGH (Yamuna Floodplain Surcharge & Ring Road Ponding)",
        "trend": "Rising Slowly (Hathnikund Barrage discharge)",
        "floodProneZones": [
            "Yamuna Floodplains & Kashmere Gate",
            "Minto Bridge Underpass",
            "ITO Junction Corridor",
            "Pragati Maidan Tunnel"
        ],
        "roadsAffected": 16,
        "hospitalsAtRisk": 2,
        "transportImpact": "Ring Road Kashmere Gate section restricted; Minto Bridge vehicular transit closed",
        "powerRisk": "Old Delhi substation flood wall sandbagged",
        "shelters": 58,
        "sheltersActive": 22,
        "emergencyVehicles": 62,
        "responseTeams": 12,
        "criticalWarnings": "Yamuna river level at Old Railway Bridge reached 205.80m (Warning Mark: 205.33m).",
        "riverCatchment": "Yamuna River Drainage Basin",
        "explanation": "Upstream barrage discharge coupled with localized heavy precipitation has saturated the Yamuna riverbed, causing backflow into low-elevation storm culverts across North and East Delhi."
    },
    {
        "id": "bengaluru",
        "name": "Bengaluru",
        "state": "Karnataka",
        "region": "South Deccan",
        "center": [12.9716, 77.5946],
        "coordinates": {"x": 38, "y": 78},
        "floodRisk": "HIGH",
        "riskColor": "#ff7700",
        "rainfall": 48.0,
        "rainfallStr": "48.0 mm/hr",
        "activeAlerts": 7,
        "affectedZones": 15,
        "infrastructureRisk": 6,
        "readiness": 70,
        "inundation": 0.85,
        "waterloggingSeverity": "HIGH (SWD Rajakaluve Encroachments & Lake Cascades)",
        "trend": "Sustained Inflow",
        "floodProneZones": [
            "Bellandur Lake Buffer Basin",
            "Mahadevapura Outer Ring Road",
            "Manyata Tech Park Gateway",
            "HBR Layout Lowlands"
        ],
        "roadsAffected": 19,
        "hospitalsAtRisk": 1,
        "transportImpact": "Outer Ring Road (ORR) flooded near Ecospace; major tech corridors moving slowly",
        "powerRisk": "BESCOM transformers submerged in Mahadevapura",
        "shelters": 34,
        "sheltersActive": 10,
        "emergencyVehicles": 45,
        "responseTeams": 10,
        "criticalWarnings": "Bellandur lake cascading weir overflowing across Sarjapur arterial link.",
        "riverCatchment": "Vrishabhavathi & Dakshina Pinakini Basins",
        "explanation": "Inter-connected lake series have reached full reservoir capacity, resulting in surface runoff overtopping arterial ring roads due to secondary storm drain constrictions."
    },
    {
        "id": "chennai",
        "name": "Chennai",
        "state": "Tamil Nadu",
        "region": "Coromandel Coast",
        "center": [13.0827, 80.2707],
        "coordinates": {"x": 48, "y": 79},
        "floodRisk": "CRITICAL",
        "riskColor": "#ff334b",
        "rainfall": 74.0,
        "rainfallStr": "74.0 mm/hr",
        "activeAlerts": 14,
        "affectedZones": 22,
        "infrastructureRisk": 9,
        "readiness": 85,
        "inundation": 1.60,
        "waterloggingSeverity": "EXTREME (Adyar & Cooum Overtopping + North East Monsoon)",
        "trend": "Surging Rapidly (+18 mm/hr)",
        "floodProneZones": [
            "Velachery Lake Basin",
            "Mudichur & Tambaram Lowlands",
            "Madipakkam Residential Catchment",
            "Perumbakkam Marshland"
        ],
        "roadsAffected": 28,
        "hospitalsAtRisk": 5,
        "transportImpact": "Suburban train slow lines halted; GST Road waterlogged near airport approach",
        "powerRisk": "TANGEDCO precautionary power cutoff across 8 waterlogged wards",
        "shelters": 80,
        "sheltersActive": 38,
        "emergencyVehicles": 110,
        "responseTeams": 24,
        "criticalWarnings": "Chembarambakkam Lake discharge increased to 6,000 cusecs into Adyar River.",
        "riverCatchment": "Adyar, Cooum & Kosasthalaiyar River Basins",
        "explanation": "Heavy coastal convective cloud clusters combined with controlled reservoir releases have elevated water levels across southern catchments, requiring high-priority dewatering deployment."
    },
    {
        "id": "kolkata",
        "name": "Kolkata",
        "state": "West Bengal",
        "region": "East Delta",
        "center": [22.5726, 88.3639],
        "coordinates": {"x": 74, "y": 48},
        "floodRisk": "HIGH",
        "riskColor": "#ff7700",
        "rainfall": 58.0,
        "rainfallStr": "58.0 mm/hr",
        "activeAlerts": 9,
        "affectedZones": 14,
        "infrastructureRisk": 6,
        "readiness": 74,
        "inundation": 1.10,
        "waterloggingSeverity": "HIGH (Hooghly High Tide Lock & Circular Canal Inundation)",
        "trend": "Surging with Tide (+10 mm/hr)",
        "floodProneZones": [
            "Behala & Taratala Lowlands",
            "Central Avenue & College Street",
            "Thanthania Kalibari Basin",
            "Park Circus Connector"
        ],
        "roadsAffected": 17,
        "hospitalsAtRisk": 3,
        "transportImpact": "Tram lines submerged in Central Kolkata; Circular Railway operations delayed",
        "powerRisk": "CESC low-lying feeder distribution boxes isolated in Behala",
        "shelters": 48,
        "sheltersActive": 18,
        "emergencyVehicles": 55,
        "responseTeams": 14,
        "criticalWarnings": "Hooghly River tidal lock active until 16:30 IST. Lock gates shut at Palmer Bridge.",
        "riverCatchment": "Hooghly Estuary & East Kolkata Wetlands",
        "explanation": "High tide in the Hooghly estuary prevents gravity outflow through historical sluice channels, causing sustained ponding across central and southern commercial districts."
    },
    {
        "id": "hyderabad",
        "name": "Hyderabad",
        "state": "Telangana",
        "region": "South Central",
        "center": [17.3850, 78.4867],
        "coordinates": {"x": 40, "y": 62},
        "floodRisk": "MODERATE",
        "riskColor": "#ffaa00",
        "rainfall": 42.0,
        "rainfallStr": "42.0 mm/hr",
        "activeAlerts": 5,
        "affectedZones": 9,
        "infrastructureRisk": 4,
        "readiness": 80,
        "inundation": 0.50,
        "waterloggingSeverity": "MODERATE (Musi River Surcharge & Nullah Chokepoints)",
        "trend": "Steady / Normalizing",
        "floodProneZones": [
            "Musi Riverbank Chaderghat",
            "Begumpet Nullah Lowlands",
            "Tolichowki / Nadeem Colony",
            "Alwal Lake Catchment"
        ],
        "roadsAffected": 10,
        "hospitalsAtRisk": 1,
        "transportImpact": "PVNR Expressway access slow; Chaderghat causeway traffic diverted",
        "powerRisk": "TSSPDCL substation dry and operational",
        "shelters": 30,
        "sheltersActive": 8,
        "emergencyVehicles": 40,
        "responseTeams": 8,
        "criticalWarnings": "Himayat Sagar & Osman Sagar lake gates discharging 1,200 cusecs into Musi.",
        "riverCatchment": "Musi River Basin",
        "explanation": "Controlled reservoir sluice operations are effectively managing river discharge, with localized waterlogging confined to natural stream chokepoints and depressed junctions."
    },
    {
        "id": "ahmedabad",
        "name": "Ahmedabad",
        "state": "Gujarat",
        "region": "West",
        "center": [23.0225, 72.5714],
        "coordinates": {"x": 23, "y": 44},
        "floodRisk": "MODERATE",
        "riskColor": "#ffaa00",
        "rainfall": 34.0,
        "rainfallStr": "34.0 mm/hr",
        "activeAlerts": 4,
        "affectedZones": 7,
        "infrastructureRisk": 3,
        "readiness": 88,
        "inundation": 0.40,
        "waterloggingSeverity": "MODERATE (Sabarmati Controlled Outflow & Underpass Ponding)",
        "trend": "Receding Slowly",
        "floodProneZones": [
            "Akhbarnagar Underpass",
            "Mithakhali Underpass",
            "Vastrapur Lake Lowland",
            "Gota Canal Basin"
        ],
        "roadsAffected": 6,
        "hospitalsAtRisk": 0,
        "transportImpact": "Akhbarnagar underpass barricaded; BRTS corridors fully operational",
        "powerRisk": "Torrent Power grid stable",
        "shelters": 28,
        "sheltersActive": 5,
        "emergencyVehicles": 38,
        "responseTeams": 6,
        "criticalWarnings": "Vasna Barrage opened 6 gates to maintain Sabarmati River level at 128 feet.",
        "riverCatchment": "Sabarmati River Basin",
        "explanation": "Automated stormwater pumping across major railway underpasses has minimized urban disruption, while the Vasna barrage maintains optimal river channel discharge."
    },
    {
        "id": "pune",
        "name": "Pune",
        "state": "Maharashtra",
        "region": "Western Ghats",
        "center": [18.5204, 73.8567],
        "coordinates": {"x": 30, "y": 60},
        "floodRisk": "MODERATE",
        "riskColor": "#ffaa00",
        "rainfall": 38.0,
        "rainfallStr": "38.0 mm/hr",
        "activeAlerts": 6,
        "affectedZones": 8,
        "infrastructureRisk": 4,
        "readiness": 84,
        "inundation": 0.60,
        "waterloggingSeverity": "MODERATE (Mutha River Discharge from Khadakwasla Dam)",
        "trend": "Holding Steady",
        "floodProneZones": [
            "Sinhagad Road Riverside Societies",
            "Bhide Bridge Causeway",
            "Ambil Odha Stream",
            "Sangvi Bridge"
        ],
        "roadsAffected": 8,
        "hospitalsAtRisk": 0,
        "transportImpact": "Bhide low-level causeway submerged; Deccan Gymkhana traffic rerouted",
        "powerRisk": "MSEDCL riverside DP boxes shut down as safety precaution",
        "shelters": 26,
        "sheltersActive": 7,
        "emergencyVehicles": 35,
        "responseTeams": 7,
        "criticalWarnings": "Khadakwasla Dam releasing 13,800 cusecs into Mutha River riverbed.",
        "riverCatchment": "Mula-Mutha River Basin",
        "explanation": "Dam releases along the Mutha river corridor have submerged low-level causeways, while inland stormwater drainage networks are maintaining satisfactory clearance."
    },
    {
        "id": "guwahati",
        "name": "Guwahati",
        "state": "Assam",
        "region": "Northeast",
        "center": [26.1445, 91.7362],
        "coordinates": {"x": 88, "y": 32},
        "floodRisk": "CRITICAL",
        "riskColor": "#ff334b",
        "rainfall": 82.0,
        "rainfallStr": "82.0 mm/hr",
        "activeAlerts": 16,
        "affectedZones": 24,
        "infrastructureRisk": 8,
        "readiness": 78,
        "inundation": 1.80,
        "waterloggingSeverity": "EXTREME (Brahmaputra Flood Wave + Hill Slush Runoff)",
        "trend": "Surging Heavily (+22 mm/hr)",
        "floodProneZones": [
            "Anil Nagar & Nabin Nagar Lowlands",
            "Rukminigaon & VIP Road",
            "Bharalu River Corridor",
            "Zoo Road & Chandmari"
        ],
        "roadsAffected": 26,
        "hospitalsAtRisk": 4,
        "transportImpact": "GS Road submerged near Rukminigaon; state transport halted on 6 routes",
        "powerRisk": "APDCL power lines snapped by soil slush in 3 hill areas",
        "shelters": 65,
        "sheltersActive": 32,
        "emergencyVehicles": 72,
        "responseTeams": 22,
        "criticalWarnings": "Brahmaputra water level at DC Court gauge flowing 1.25m above Danger Mark.",
        "riverCatchment": "Brahmaputra River & Bharalu Channel",
        "explanation": "Intense downpours on surrounding Meghalaya hills have triggered rapid sediment runoff into city nullahs, exacerbating river backflow from the swollen Brahmaputra."
    },
    {
        "id": "patna",
        "name": "Patna",
        "state": "Bihar",
        "region": "Gangetic Plains",
        "center": [25.5941, 85.1376],
        "coordinates": {"x": 62, "y": 36},
        "floodRisk": "HIGH",
        "riskColor": "#ff7700",
        "rainfall": 60.0,
        "rainfallStr": "60.0 mm/hr",
        "activeAlerts": 10,
        "affectedZones": 16,
        "infrastructureRisk": 7,
        "readiness": 72,
        "inundation": 1.20,
        "waterloggingSeverity": "HIGH (Ganga River Surcharge & Heavy Sump Strain)",
        "trend": "Rising (+8 mm/hr)",
        "floodProneZones": [
            "Rajendra Nagar Bowl Basin",
            "Kankarbagh Lowlands",
            "Boring Road Underpass",
            "Saidpur Sump Outfall"
        ],
        "roadsAffected": 21,
        "hospitalsAtRisk": 3,
        "transportImpact": "Rajendra Nagar Terminal approach road waterlogged 0.8m",
        "powerRisk": "South Bihar Power Co sump sub-stations on generator power",
        "shelters": 52,
        "sheltersActive": 24,
        "emergencyVehicles": 58,
        "responseTeams": 15,
        "criticalWarnings": "Ganga water level at Digha Ghat is 0.42m above Danger Level, locking gravity sluices.",
        "riverCatchment": "Ganga, Punpun & Son Confluence",
        "explanation": "Depression bowl topography across southern wards creates severe drainage dependency on motorized sump stations as high Ganga water levels prevent natural gravity runoff."
    }
]

# =====================================================================
# 2. SEED ZONES DATA
# =====================================================================
ZONES_DATA: List[Dict[str, Any]] = [
    {
        "id": "ZONE-KUR-01",
        "city_id": "mumbai",
        "name": "Kurla West & Mithi Basin Zone",
        "wardCode": "L-Ward",
        "code": "L-Ward",
        "zoneCategory": "Riverine & Lowland Inundation",
        "riskLevel": "CRITICAL",
        "riskScore": 92,
        "floodProbability": 96,
        "expectedOnset": "Immediate (Active Overflow)",
        "leadTimeToFlood": "Immediate (Active)",
        "waterLevelM": 3.42,
        "warningLevelM": 2.70,
        "dangerLevelM": 3.00,
        "waterDepthM": 1.45,
        "inundationDepthM": 1.25,
        "dangerMarkM": 1.00,
        "rainfallRateMmHr": 68.0,
        "currentRainfall": 68.0,
        "drainageCapacityLPS": 24000,
        "drainageBlockagePct": 65,
        "populationAtRisk": 86000,
        "affectedPopulation": 86000,
        "pumpsOperating": "4 / 4",
        "criticalHotspots": ["Kranti Nagar", "Bail Bazar", "LBS Road Jn", "Chunabhatti"],
        "evacuationStatus": "EVACUATION_IN_PROGRESS",
        "trend": "RISING",
        "statusNote": "Mithi River water spilling over banks near Kranti Nagar. Evacuation underway.",
        "description": "Mithi River water spilling over banks into residential settlements. Storm drains locked by high water surface elevation.",
        "recommendedAction": "Evacuate ground floors to Kurla Municipal High School. Deploy 4 high-head dewatering pumps.",
        "center": [19.0688, 72.8797],
        "coordinates": {"lat": 19.0688, "lng": 72.8797},
        "elevationAMSL": 2.4,
        "imperviousPct": 88,
        "historicalInundations5Yr": 14,
        "polygonCoords": [
            [19.0820, 72.8680],
            [19.0840, 72.8920],
            [19.0680, 72.8980],
            [19.0560, 72.8850],
            [19.0580, 72.8690]
        ]
    },
    {
        "id": "ZONE-HIN-02",
        "city_id": "mumbai",
        "name": "Hindmata & Dadar TT Lowland",
        "wardCode": "F/North Ward",
        "code": "F/North Ward",
        "zoneCategory": "Topographic Bowl & Tidal Lock",
        "riskLevel": "CRITICAL",
        "riskScore": 89,
        "floodProbability": 92,
        "expectedOnset": "Active Waterlogging",
        "leadTimeToFlood": "Active Waterlogging",
        "waterLevelM": 2.95,
        "warningLevelM": 2.20,
        "dangerLevelM": 2.50,
        "waterDepthM": 1.40,
        "inundationDepthM": 1.40,
        "dangerMarkM": 0.80,
        "rainfallRateMmHr": 54.5,
        "currentRainfall": 54.5,
        "drainageCapacityLPS": 36000,
        "drainageBlockagePct": 50,
        "populationAtRisk": 64000,
        "affectedPopulation": 64000,
        "pumpsOperating": "6 / 6",
        "criticalHotspots": ["Hindmata Underpass", "Dadar TT Circle", "Parel TT"],
        "evacuationStatus": "TRAFFIC_DIVERTED",
        "trend": "STABLE_HIGH",
        "statusNote": "Britannia pumping station operating at 100% capacity. Gravity drain locked by high tide.",
        "description": "Gravitational outfalls blocked by 3.82m sea tide. Britannia pumping station operating at 100% capacity.",
        "recommendedAction": "Keep all 6 Britannia turbine pumps at maximum RPM. Divert traffic to Lalbaug flyover.",
        "center": [19.0178, 72.8478],
        "coordinates": {"lat": 19.0178, "lng": 72.8478},
        "elevationAMSL": 1.8,
        "imperviousPct": 94,
        "historicalInundations5Yr": 18,
        "polygonCoords": [
            [19.0280, 72.8380],
            [19.0290, 72.8580],
            [19.0110, 72.8600],
            [19.0060, 72.8440],
            [19.0150, 72.8360]
        ]
    },
    {
        "id": "ZONE-MIL-03",
        "city_id": "mumbai",
        "name": "Milan & Khar Subway Corridor",
        "wardCode": "H/West Ward",
        "code": "H/West Ward",
        "zoneCategory": "Railway Underpass Dip",
        "riskLevel": "HIGH",
        "riskScore": 81,
        "floodProbability": 84,
        "expectedOnset": "T+15 mins",
        "leadTimeToFlood": "18 mins",
        "waterLevelM": 2.65,
        "warningLevelM": 1.90,
        "dangerLevelM": 2.20,
        "waterDepthM": 0.95,
        "inundationDepthM": 0.95,
        "dangerMarkM": 0.50,
        "rainfallRateMmHr": 51.0,
        "currentRainfall": 51.0,
        "drainageCapacityLPS": 18000,
        "drainageBlockagePct": 40,
        "populationAtRisk": 42000,
        "affectedPopulation": 42000,
        "pumpsOperating": "3 / 4",
        "criticalHotspots": ["Milan Subway", "S.V. Road Khar", "Gazdarbandh Nullah"],
        "evacuationStatus": "BARRICADED",
        "trend": "RISING",
        "statusNote": "Traffic diverted via flyover. Submersible de-watering pumps deployed.",
        "description": "Severe water accumulation inside subway underpass. Automatic boom barriers activated.",
        "recommendedAction": "Operate Gazdarbandh outfall pumps. Maintain vehicular closure until depth < 0.3m.",
        "center": [19.0833, 72.8398],
        "coordinates": {"lat": 19.0833, "lng": 72.8398},
        "elevationAMSL": 2.0,
        "imperviousPct": 91,
        "historicalInundations5Yr": 12,
        "polygonCoords": [
            [19.0940, 72.8310],
            [19.0950, 72.8480],
            [19.0760, 72.8510],
            [19.0730, 72.8340]
        ]
    },
    {
        "id": "ZONE-SIO-04",
        "city_id": "mumbai",
        "name": "Sion Circle & Gandhi Market",
        "wardCode": "F/North Ward",
        "code": "F/North Ward",
        "zoneCategory": "Arterial Road Sump",
        "riskLevel": "HIGH",
        "riskScore": 79,
        "floodProbability": 79,
        "expectedOnset": "T+25 mins",
        "leadTimeToFlood": "30 mins",
        "waterLevelM": 2.45,
        "warningLevelM": 1.95,
        "dangerLevelM": 2.25,
        "waterDepthM": 0.80,
        "inundationDepthM": 0.80,
        "dangerMarkM": 0.50,
        "rainfallRateMmHr": 49.0,
        "currentRainfall": 49.0,
        "drainageCapacityLPS": 20000,
        "drainageBlockagePct": 45,
        "populationAtRisk": 51000,
        "affectedPopulation": 51000,
        "pumpsOperating": "3 / 4",
        "criticalHotspots": ["Gandhi Market", "Sion Railway Station Track 2", "Sion Circle"],
        "evacuationStatus": "MONITORING",
        "trend": "RISING",
        "statusNote": "Central Railway slow line speed restricted to 20 kmph due to track waterlogging.",
        "description": "Waterlogging along Central Railway tracks and Dr. B.A. Road. Train speeds restricted to 20 kmph.",
        "recommendedAction": "Deploy mobile trailer-mounted high-flow pumps to Gandhi Market drain sump.",
        "center": [19.0400, 72.8600],
        "coordinates": {"lat": 19.0400, "lng": 72.8600},
        "elevationAMSL": 2.8,
        "imperviousPct": 86,
        "historicalInundations5Yr": 11,
        "polygonCoords": [
            [19.0490, 72.8510],
            [19.0510, 72.8710],
            [19.0320, 72.8720],
            [19.0300, 72.8530]
        ]
    },
    {
        "id": "ZONE-AND-05",
        "city_id": "mumbai",
        "name": "Andheri East-West Subway",
        "wardCode": "K/East Ward",
        "code": "K/East Ward",
        "zoneCategory": "Underpass Drainage Basin",
        "riskLevel": "MODERATE",
        "riskScore": 62,
        "floodProbability": 62,
        "expectedOnset": "T+45 mins",
        "leadTimeToFlood": "25 mins",
        "waterLevelM": 2.35,
        "warningLevelM": 1.80,
        "dangerLevelM": 2.10,
        "waterDepthM": 0.45,
        "inundationDepthM": 0.85,
        "dangerMarkM": 0.50,
        "rainfallRateMmHr": 46.2,
        "currentRainfall": 46.2,
        "drainageCapacityLPS": 16000,
        "drainageBlockagePct": 30,
        "populationAtRisk": 38000,
        "affectedPopulation": 38000,
        "pumpsOperating": "3 / 3",
        "criticalHotspots": ["Andheri Subway", "WEH Junction"],
        "evacuationStatus": "WARNING_POSTED",
        "trend": "RISING",
        "statusNote": "Subway closed for vehicular traffic. Water accumulation in pedestrian underpass.",
        "description": "Moderate water ingress from surrounding elevated railway tracks. Auxiliary pump active.",
        "recommendedAction": "Prepare boom barrier lockdown if precipitation rate exceeds 50 mm/hr.",
        "center": [19.1197, 72.8464],
        "coordinates": {"lat": 19.1197, "lng": 72.8464},
        "elevationAMSL": 3.2,
        "imperviousPct": 84,
        "historicalInundations5Yr": 8,
        "polygonCoords": [
            [19.1310, 72.8360],
            [19.1320, 72.8580],
            [19.1110, 72.8600],
            [19.1090, 72.8380]
        ]
    },
    {
        "id": "ZONE-BKC-06",
        "city_id": "mumbai",
        "name": "Bandra-Kurla Complex (BKC)",
        "wardCode": "H/East Ward",
        "code": "H/East Ward",
        "zoneCategory": "Channelized Commercial Basin",
        "riskLevel": "MODERATE",
        "riskScore": 58,
        "floodProbability": 48,
        "expectedOnset": "T+1 hr",
        "leadTimeToFlood": "55 mins",
        "waterLevelM": 1.65,
        "warningLevelM": 2.10,
        "dangerLevelM": 2.50,
        "waterDepthM": 0.25,
        "inundationDepthM": 0.25,
        "dangerMarkM": 0.60,
        "rainfallRateMmHr": 38.0,
        "currentRainfall": 38.0,
        "drainageCapacityLPS": 32000,
        "drainageBlockagePct": 20,
        "populationAtRisk": 28000,
        "affectedPopulation": 28000,
        "pumpsOperating": "4 / 4",
        "criticalHotspots": ["Kalanagar Junction", "Vakola Outfall"],
        "evacuationStatus": "CLEAR",
        "trend": "SLOW_RISING",
        "statusNote": "Vakola Nullah discharge flowing at 75% capacity. Water levels within buffer margins.",
        "description": "Vakola Nullah carrying high discharge but flowing smoothly. No major road blockages.",
        "recommendedAction": "Monitor Vakola water level sensor SEN-FLW-01.",
        "center": [19.0607, 72.8662],
        "coordinates": {"lat": 19.0607, "lng": 72.8662},
        "elevationAMSL": 4.2,
        "imperviousPct": 80,
        "historicalInundations5Yr": 3,
        "polygonCoords": [
            [19.0690, 72.8540],
            [19.0710, 72.8760],
            [19.0520, 72.8780],
            [19.0510, 72.8560]
        ]
    },
    {
        "id": "ZONE-CHE-07",
        "city_id": "mumbai",
        "name": "Chembur Postal Colony",
        "wardCode": "M/West Ward",
        "code": "M/West Ward",
        "zoneCategory": "Suburban Lowland",
        "riskLevel": "LOW",
        "riskScore": 38,
        "floodProbability": 28,
        "expectedOnset": "> 2 hrs",
        "leadTimeToFlood": "> 2 hrs",
        "waterLevelM": 1.15,
        "warningLevelM": 1.90,
        "dangerLevelM": 2.30,
        "waterDepthM": 0.10,
        "inundationDepthM": 0.10,
        "dangerMarkM": 0.50,
        "rainfallRateMmHr": 28.5,
        "currentRainfall": 28.5,
        "drainageCapacityLPS": 15000,
        "drainageBlockagePct": 15,
        "populationAtRisk": 11000,
        "affectedPopulation": 11000,
        "pumpsOperating": "2 / 2",
        "criticalHotspots": ["Postal Colony Low Grounds", "Shell Colony"],
        "evacuationStatus": "CLEAR",
        "trend": "STABLE",
        "statusNote": "Storm drains operating normally. No major road inundation reported.",
        "description": "Storm drainage network functioning smoothly. Minor curb puddling only.",
        "recommendedAction": "Routine trash rack cleaning at collection culverts.",
        "center": [19.0522, 72.8994],
        "coordinates": {"lat": 19.0522, "lng": 72.8994},
        "elevationAMSL": 6.5,
        "imperviousPct": 72,
        "historicalInundations5Yr": 2,
        "polygonCoords": [
            [19.0610, 72.8890],
            [19.0630, 72.9090],
            [19.0430, 72.9120],
            [19.0410, 72.8910]
        ]
    },
    {
        "id": "ZONE-COL-08",
        "city_id": "mumbai",
        "name": "Colaba & Marine Lines",
        "wardCode": "A-Ward",
        "code": "A-Ward",
        "zoneCategory": "Coastal Island City",
        "riskLevel": "SAFE",
        "riskScore": 22,
        "floodProbability": 12,
        "expectedOnset": "None",
        "leadTimeToFlood": "None",
        "waterLevelM": 0.70,
        "warningLevelM": 2.00,
        "dangerLevelM": 2.50,
        "waterDepthM": 0.00,
        "inundationDepthM": 0.00,
        "dangerMarkM": 0.60,
        "rainfallRateMmHr": 22.0,
        "currentRainfall": 22.0,
        "drainageCapacityLPS": 28000,
        "drainageBlockagePct": 10,
        "populationAtRisk": 0,
        "affectedPopulation": 0,
        "pumpsOperating": "2 / 2",
        "criticalHotspots": ["None reported"],
        "evacuationStatus": "CLEAR",
        "trend": "FALLING",
        "statusNote": "Direct sea outfalls clear. Free gravitational runoff.",
        "description": "Direct sea gravity outfalls functioning normally. No flood risk.",
        "recommendedAction": "Maintain coastal watch for high tide surge.",
        "center": [18.9067, 72.8147],
        "coordinates": {"lat": 18.9067, "lng": 72.8147},
        "elevationAMSL": 5.8,
        "imperviousPct": 85,
        "historicalInundations5Yr": 0,
        "polygonCoords": [
            [18.9300, 72.8050],
            [18.9350, 72.8300],
            [18.8950, 72.8350],
            [18.8900, 72.8100]
        ]
    }
]

# =====================================================================
# 3. SEED SENSORS DATA
# =====================================================================
SENSORS_DATA: List[Dict[str, Any]] = [
    {
        "id": "SEN-RAD-01",
        "city_id": "mumbai",
        "name": "Mithi River CSIA Bridge Gauge",
        "type": "RIVER_WATER_LEVEL",
        "category": "Radar Ultrasonic",
        "lat": 19.0722,
        "lng": 72.8750,
        "ward": "Kurla West",
        "currentValue": "3.42 m",
        "rawNumeric": 3.42,
        "unit": "m",
        "warningThreshold": 2.70,
        "dangerThreshold": 3.00,
        "status": "CRITICAL",
        "batteryPct": 96,
        "lastPingSecAgo": 4,
        "trend": "+0.18 m/hr"
    },
    {
        "id": "SEN-RAD-02",
        "city_id": "mumbai",
        "name": "Hindmata Storm Drain Trunk Sensor",
        "type": "CULVERT_DEPTH",
        "category": "Submersible Pressure",
        "lat": 19.0180,
        "lng": 72.8485,
        "ward": "Hindmata",
        "currentValue": "2.95 m",
        "rawNumeric": 2.95,
        "unit": "m",
        "warningThreshold": 2.20,
        "dangerThreshold": 2.50,
        "status": "CRITICAL",
        "batteryPct": 88,
        "lastPingSecAgo": 8,
        "trend": "+0.12 m/hr"
    },
    {
        "id": "SEN-AWS-01",
        "city_id": "mumbai",
        "name": "Dadar Automated Weather Station",
        "type": "PRECIPITATION_INTENSITY",
        "category": "Tipping Bucket AWS",
        "lat": 19.0210,
        "lng": 72.8420,
        "ward": "Dadar",
        "currentValue": "58.4 mm/h",
        "rawNumeric": 58.4,
        "unit": "mm/h",
        "warningThreshold": 40.0,
        "dangerThreshold": 60.0,
        "status": "WARNING",
        "batteryPct": 100,
        "lastPingSecAgo": 12,
        "trend": "+6.2 mm/h"
    },
    {
        "id": "SEN-AWS-02",
        "city_id": "mumbai",
        "name": "Santacruz Doppler Radar AWS",
        "type": "PRECIPITATION_INTENSITY",
        "category": "Optical Disdrometer",
        "lat": 19.0880,
        "lng": 72.8450,
        "ward": "Santacruz",
        "currentValue": "71.0 mm/h",
        "rawNumeric": 71.0,
        "unit": "mm/h",
        "warningThreshold": 40.0,
        "dangerThreshold": 60.0,
        "status": "CRITICAL",
        "batteryPct": 94,
        "lastPingSecAgo": 2,
        "trend": "+14.0 mm/h"
    },
    {
        "id": "SEN-FLW-01",
        "city_id": "mumbai",
        "name": "Vakola Nullah Outflow Velocity",
        "type": "DRAINAGE_DISCHARGE",
        "category": "Doppler Flowmeter",
        "lat": 19.0640,
        "lng": 72.8590,
        "ward": "BKC",
        "currentValue": "42.8 m³/s",
        "rawNumeric": 42.8,
        "unit": "m³/s",
        "warningThreshold": 35.0,
        "dangerThreshold": 48.0,
        "status": "WARNING",
        "batteryPct": 91,
        "lastPingSecAgo": 15,
        "trend": "+3.4 m³/s"
    },
    {
        "id": "SEN-TID-01",
        "city_id": "mumbai",
        "name": "Mahim Bay Coastal Tide Gauge",
        "type": "SEA_TIDE_LEVEL",
        "category": "Acoustic Tide Sensor",
        "lat": 19.0410,
        "lng": 72.8360,
        "ward": "Mahim",
        "currentValue": "3.82 m",
        "rawNumeric": 3.82,
        "unit": "m CD",
        "warningThreshold": 3.50,
        "dangerThreshold": 4.20,
        "status": "WARNING",
        "batteryPct": 99,
        "lastPingSecAgo": 6,
        "trend": "+0.45 m (Rising Tide)"
    }
]

# =====================================================================
# 4. SEED INFRASTRUCTURE ASSETS DATA
# =====================================================================
INFRASTRUCTURE_DATA: List[Dict[str, Any]] = [
    {
        "id": "INF-PUMP-01",
        "city_id": "mumbai",
        "name": "Britannia Stormwater Pumping Station",
        "type": "HEAVY_PUMP_STATION",
        "category": "Drainage Facility",
        "categoryType": "DRAINAGE",
        "location": "Reay Road / Britannia Jn",
        "ward": "F/South Ward",
        "nearbyFloodZone": "Hindmata & Dadar TT Lowland",
        "currentFloodRisk": "HIGH",
        "impactSeverity": "HIGH",
        "operationalStatus": "Operational Max (6/6 Turbines)",
        "operationalStatusType": "OPERATIONAL",
        "installedPumps": 6,
        "activePumps": 6,
        "totalCapacityLPS": 36000,
        "currentDischargeLPS": 35200,
        "estimatedWaterDepthM": 1.10,
        "safeThresholdM": 1.50,
        "dailyUsersAffected": 250000,
        "operator": "Storm Water Drains (SWD) Department, BMC",
        "contactDesk": "+91 22 2371 4422 / Chief Engineer SWD",
        "powerSource": "Dual Grid + 1500kVA Diesel Generator (Online)",
        "status": "OPERATIONAL_MAX",
        "waterInflowLevelM": 3.10,
        "dischargeOutfall": "Mumbai Harbour Basin",
        "lastMaintenance": "2026-08-10",
        "scadaControlled": True,
        "healthScore": 97,
        "riskDimensions": {
            "accessDisruption": 40,
            "structuralExposure": 60,
            "utilityDisruption": 20,
            "emergencyImportance": 96
        }
    },
    {
        "id": "INF-PUMP-02",
        "city_id": "mumbai",
        "name": "Haji Ali Stormwater Pumping Station",
        "type": "HEAVY_PUMP_STATION",
        "category": "Drainage Facility",
        "categoryType": "DRAINAGE",
        "location": "Haji Ali Bay Outfall",
        "ward": "D-Ward",
        "nearbyFloodZone": "Haji Ali Coastal Basin",
        "currentFloodRisk": "LOW",
        "impactSeverity": "LOW",
        "operationalStatus": "Operational (5/6 Pumps Active)",
        "operationalStatusType": "OPERATIONAL",
        "installedPumps": 6,
        "activePumps": 5,
        "totalCapacityLPS": 36000,
        "currentDischargeLPS": 29800,
        "estimatedWaterDepthM": 0.30,
        "safeThresholdM": 1.20,
        "dailyUsersAffected": 180000,
        "operator": "BMC Storm Water Drains",
        "contactDesk": "+91 22 2351 7788 / Station Supt",
        "powerSource": "Grid Power Normal",
        "status": "OPERATIONAL",
        "waterInflowLevelM": 2.20,
        "dischargeOutfall": "Arabian Sea (Direct)",
        "lastMaintenance": "2026-08-14",
        "scadaControlled": True,
        "healthScore": 92,
        "riskDimensions": {
            "accessDisruption": 15,
            "structuralExposure": 25,
            "utilityDisruption": 10,
            "emergencyImportance": 85
        }
    },
    {
        "id": "INF-TRN-01",
        "city_id": "mumbai",
        "name": "Kurla Railway Station (Central & Harbour)",
        "type": "TRANSIT_LIFELINE",
        "category": "Transit Lifeline",
        "categoryType": "TRANSIT",
        "location": "Kurla West (L-Ward)",
        "ward": "Kurla West (L-Ward)",
        "nearbyFloodZone": "Kurla West & Mithi River Basin Zone",
        "currentFloodRisk": "CRITICAL",
        "impactSeverity": "CRITICAL",
        "operationalStatus": "Service Restricted",
        "operationalStatusType": "RESTRICTED",
        "estimatedWaterDepthM": 0.85,
        "safeThresholdM": 0.20,
        "dailyUsersAffected": 380000,
        "operator": "Central Railway Mumbai Division",
        "contactDesk": "+91 22 2503 2345 / Disaster Cell",
        "status": "RESTRICTED",
        "riskDimensions": {
            "accessDisruption": 90,
            "structuralExposure": 75,
            "utilityDisruption": 65,
            "emergencyImportance": 98
        }
    },
    {
        "id": "INF-HOSP-01",
        "city_id": "mumbai",
        "name": "Lokmanya Tilak Municipal Hospital (Sion Hospital)",
        "type": "CRITICAL_HEALTHCARE",
        "category": "Critical Healthcare",
        "categoryType": "HEALTHCARE",
        "location": "Sion West (F/North Ward)",
        "ward": "Sion West (F/North Ward)",
        "nearbyFloodZone": "Sion Circle & Gandhi Market Basin",
        "currentFloodRisk": "CRITICAL",
        "impactSeverity": "CRITICAL",
        "operationalStatus": "Barrier Deployed (Ambulances Only)",
        "operationalStatusType": "RESTRICTED",
        "estimatedWaterDepthM": 0.45,
        "safeThresholdM": 0.15,
        "dailyUsersAffected": 12000,
        "operator": "Brihanmumbai Municipal Corporation (BMC)",
        "contactDesk": "+91 22 2407 6381 / Casualty Wing",
        "status": "RESTRICTED",
        "riskDimensions": {
            "accessDisruption": 85,
            "structuralExposure": 40,
            "utilityDisruption": 30,
            "emergencyImportance": 100
        }
    }
]

# =====================================================================
# 5. SEED DRAINAGE NODES DATA
# =====================================================================
DRAINAGE_NODES_DATA: List[Dict[str, Any]] = [
    {
        "id": "DRN-MITHI-01",
        "city_id": "mumbai",
        "name": "Mithi River Main Outfall Trunk Junction",
        "type": "TRUNK_OUTFALL",
        "typeLabel": "Primary Riverine Outfall",
        "lat": 19.0722,
        "lng": 72.8750,
        "ward": "Kurla West",
        "capacityM3s": 120.0,
        "currentFlowM3s": 114.5,
        "blockagePct": 72,
        "siltationLevelM": 1.80,
        "waterLevelM": 3.42,
        "status": "CHOKED",
        "lastInspected": "Today, 08:30 IST",
        "sensorId": "SEN-RAD-01",
        "description": "Main stormwater discharge trunk for central suburbs. Heavy floating debris and high siltation blocking 72% cross-sectional area.",
        "actionRequired": "Deploy amphibious hydraulic excavator for immediate trash clearing."
    },
    {
        "id": "DRN-HIND-02",
        "city_id": "mumbai",
        "name": "Hindmata Storm Trunk Gravity Culvert",
        "type": "CULVERT_JUNCTION",
        "typeLabel": "Gravity Culvert Sump",
        "lat": 19.0180,
        "lng": 72.8485,
        "ward": "Hindmata & Dadar",
        "capacityM3s": 48.0,
        "currentFlowM3s": 46.2,
        "blockagePct": 52,
        "siltationLevelM": 1.10,
        "waterLevelM": 2.95,
        "status": "CHOKED",
        "lastInspected": "Today, 09:15 IST",
        "sensorId": "SEN-RAD-02",
        "description": "Gravity outflow obstructed by high tide sea level. Underground holding tank filling rapidly.",
        "actionRequired": "Maintain Britannia pumping turbines at max RPM to bypass locked gravity flow."
    },
    {
        "id": "DRN-VAK-03",
        "city_id": "mumbai",
        "name": "Vakola Nullah Drainage Channel",
        "type": "CHANNEL_NODE",
        "typeLabel": "Open Storm Channel",
        "lat": 19.0640,
        "lng": 72.8590,
        "ward": "BKC / Vakola",
        "capacityM3s": 65.0,
        "currentFlowM3s": 42.8,
        "blockagePct": 25,
        "siltationLevelM": 0.45,
        "waterLevelM": 1.65,
        "status": "HIGH_LOAD",
        "lastInspected": "Yesterday, 17:00 IST",
        "sensorId": "SEN-FLW-01",
        "description": "Flow velocity stable at 2.4 m/s. Discharging towards Mahim creek without major obstruction.",
        "actionRequired": "Monitor telemetry SEN-FLW-01 for surge onset."
    }
]

# =====================================================================
# 6. SEED ROADS DATA
# =====================================================================
ROADS_DATA: List[Dict[str, Any]] = [
    {
        "id": "RD-LBS-01",
        "city_id": "mumbai",
        "name": "Lal Bahadur Shastri (LBS) Marg - Kurla",
        "status": "SUBMERGED_CLOSED",
        "statusLabel": "Submerged & Closed",
        "riskLevel": "CRITICAL",
        "waterDepthM": 1.25,
        "speedLimitKmh": 0,
        "trafficCondition": "Completely Closed",
        "alternativeRoute": "Divert via Eastern Express Highway (EEH)",
        "coordinates": [
            [19.0820, 72.8750],
            [19.0750, 72.8780],
            [19.0680, 72.8810],
            [19.0600, 72.8830]
        ]
    },
    {
        "id": "RD-BAR-02",
        "city_id": "mumbai",
        "name": "Dr. Babasaheb Ambedkar Road - Hindmata",
        "status": "SUBMERGED_CLOSED",
        "statusLabel": "Submerged Underpass",
        "riskLevel": "CRITICAL",
        "waterDepthM": 1.40,
        "speedLimitKmh": 0,
        "trafficCondition": "Surface Road Closed (Flyover Open)",
        "alternativeRoute": "Use Hindmata Flyover overhead lanes",
        "coordinates": [
            [19.0280, 72.8460],
            [19.0220, 72.8470],
            [19.0160, 72.8480],
            [19.0100, 72.8490]
        ]
    },
    {
        "id": "RD-SVR-03",
        "city_id": "mumbai",
        "name": "Swami Vivekanand (S.V.) Road - Khar / Milan",
        "status": "WATERLOGGED_SLOW",
        "statusLabel": "Waterlogged (Slow Moving)",
        "riskLevel": "HIGH",
        "waterDepthM": 0.65,
        "speedLimitKmh": 15,
        "trafficCondition": "Heavy Water Congestion",
        "alternativeRoute": "Use Linking Road or Western Express Highway",
        "coordinates": [
            [19.0920, 72.8380],
            [19.0850, 72.8390],
            [19.0780, 72.8410],
            [19.0710, 72.8420]
        ]
    },
    {
        "id": "RD-WEH-04",
        "city_id": "mumbai",
        "name": "Western Express Highway (WEH) - Bandra to Andheri",
        "status": "CLEAR_OPEN",
        "statusLabel": "Clear & Operational",
        "riskLevel": "LOW",
        "waterDepthM": 0.05,
        "speedLimitKmh": 60,
        "trafficCondition": "Normal Monsoon Flow",
        "alternativeRoute": "Primary North-South Emergency Corridor",
        "coordinates": [
            [19.1200, 72.8520],
            [19.0950, 72.8540],
            [19.0700, 72.8560],
            [19.0550, 72.8530]
        ]
    },
    {
        "id": "RD-EEH-05",
        "city_id": "mumbai",
        "name": "Eastern Express Highway (EEH) - Sion to Ghatkopar",
        "status": "CLEAR_OPEN",
        "statusLabel": "Clear & Operational",
        "riskLevel": "LOW",
        "waterDepthM": 0.08,
        "speedLimitKmh": 60,
        "trafficCondition": "Clear Emergency Route",
        "alternativeRoute": "Primary Ambulance & Relief Route",
        "coordinates": [
            [19.0880, 72.9050],
            [19.0680, 72.8900],
            [19.0480, 72.8750],
            [19.0380, 72.8650]
        ]
    }
]

# =====================================================================
# 7. SEED ALERTS DATA
# =====================================================================
ALERTS_DATA: List[Dict[str, Any]] = [
    {
        "id": "ALT-MUM-01",
        "city_id": "mumbai",
        "capCode": "CAP-IN-MH-MUM-2026-0891",
        "title": "Mithi River Bank Breached - Immediate Evacuation Triggered",
        "location": "Kurla West & Mithi River Basin",
        "ward": "Kurla West (L-Ward)",
        "wardCode": "L-Ward",
        "alertType": "River Overflow",
        "severity": "CRITICAL",
        "status": "Active",
        "rainfallMmHr": 68.0,
        "rainfallStr": "68.0 mm/h",
        "floodProbability": 96,
        "expectedImpactTime": "Immediate (Active Overflow)",
        "leadTimeToPeak": "38 mins",
        "waterDepthM": 1.45,
        "dangerThresholdM": 1.00,
        "aiConfidence": 97,
        "affectedPopulation": 86000,
        "timestamp": "12 mins ago",
        "reportedAt": "Today, 14:18 IST",
        "source": "JALRAKSHAK AI Nowcasting Engine & Gauge SEN-RAD-01",
        "description": "Mithi River water surface level has crossed the danger mark (3.00m at 3.42m). Floodwater is breaching river retaining walls near Kranti Nagar and Bail Bazar. Immediate ground floor evacuation is active.",
        "triggerFactors": [
            {
                "id": "fac-rain-intensity",
                "name": "Rainfall Intensity",
                "measuredValue": "68.0 mm/h",
                "contributionPct": 32,
                "severity": "CRITICAL",
                "statusColor": "#ff334b",
                "explanation": "Extreme convective cloudburst rate exceeds local stormwater conduit capacity by 240%."
            },
            {
                "id": "fac-river-level",
                "name": "River Water Level Surcharge",
                "measuredValue": "3.42m (Danger: 3.00m)",
                "contributionPct": 24,
                "severity": "CRITICAL",
                "statusColor": "#ff334b",
                "explanation": "Ultrasonic radar gauge detected continuous water level rise at +0.18 m/hr."
            }
        ],
        "recommendedActions": [
            "Evacuate ground floor occupants of Kranti Nagar and Bail Bazar to Kurla Municipal School Camp",
            "Deploy 4 additional 6,000 LPS high-head submersible dewatering pumps to LBS Road",
            "Barricade LBS Marg between Kurla Station and Chunabhatti for all vehicular traffic",
            "Dispatch NDRF Battalion 04 inflatable rescue boats to Mithi riverbanks"
        ],
        "broadcastSent": True,
        "channels": ["SMS Broadcast", "Sirens", "NDRF Dispatch", "Traffic Police Feed"]
    },
    {
        "id": "ALT-MUM-02",
        "city_id": "mumbai",
        "capCode": "CAP-IN-MH-MUM-2026-0890",
        "title": "Hindmata Stormwater Gravity Outfall Locked by High Tide",
        "location": "Hindmata & Dadar TT Lowland",
        "ward": "Hindmata & Dadar TT (F/North)",
        "wardCode": "F/North Ward",
        "alertType": "Tidal Lock & Sump Overflow",
        "severity": "CRITICAL",
        "status": "Active",
        "rainfallMmHr": 54.5,
        "rainfallStr": "54.5 mm/h",
        "floodProbability": 92,
        "expectedImpactTime": "Active Waterlogging",
        "leadTimeToPeak": "25 mins",
        "waterDepthM": 1.40,
        "dangerThresholdM": 0.80,
        "aiConfidence": 95,
        "affectedPopulation": 64000,
        "timestamp": "24 mins ago",
        "reportedAt": "Today, 14:06 IST",
        "source": "Coastal Sluice SCADA Telemetry & Sensor SEN-RAD-02",
        "description": "Sea tide level at Mahim/Worli outfall has reached 3.82m CD, preventing gravitational discharge. Britannia pumping station running 6/6 heavy turbine pumps. Inundation depth at Hindmata junction reached 1.40m.",
        "triggerFactors": [
            {
                "id": "fac-tide-lock",
                "name": "River & Sea Tide Level",
                "measuredValue": "3.82m Coastal Tide",
                "contributionPct": 34,
                "severity": "CRITICAL",
                "statusColor": "#ff334b",
                "explanation": "Tidal backpressure completely blocks gravity drains, causing stormwater backflow."
            }
        ],
        "recommendedActions": [
            "Keep all 6 Britannia de-watering turbines at maximum continuous RPM",
            "Divert South-bound Dr. B.A. Road vehicular traffic onto Lalbaug flyover overhead lanes"
        ],
        "broadcastSent": True,
        "channels": ["SMS Broadcast", "Traffic Police Feed", "Municipal SCADA"]
    },
    {
        "id": "ALT-MUM-03",
        "city_id": "mumbai",
        "capCode": "CAP-IN-MH-MUM-2026-0889",
        "title": "Milan Subway Waterlogging Danger - Level Rising at +0.20m/hr",
        "location": "Milan & Khar Subway Corridor",
        "ward": "Milan & Khar (H/West)",
        "wardCode": "H/West Ward",
        "alertType": "Subway Flash Flood",
        "severity": "HIGH",
        "status": "Dispatched",
        "rainfallMmHr": 51.0,
        "rainfallStr": "51.0 mm/h",
        "floodProbability": 84,
        "expectedImpactTime": "T+15 mins",
        "leadTimeToPeak": "45 mins",
        "waterDepthM": 0.95,
        "dangerThresholdM": 0.50,
        "aiConfidence": 93,
        "affectedPopulation": 42000,
        "timestamp": "45 mins ago",
        "reportedAt": "Today, 13:45 IST",
        "source": "Computer Vision Optical Depth Camera SEN-RAD-03",
        "description": "Optical depth gauge detected water accumulation reaching 0.95m inside Milan subway. Automatic boom barriers activated for light vehicles. 3 of 4 dewatering pumps operating.",
        "triggerFactors": [
            {
                "id": "fac-elevation",
                "name": "Elevation & Underpass Dip",
                "measuredValue": "Sunken Dip (-1.2m)",
                "contributionPct": 30,
                "severity": "CRITICAL",
                "statusColor": "#ff334b",
                "explanation": "Subway underpass geometry funnels runoff from S.V. Road and railway tracks directly to floor."
            }
        ],
        "recommendedActions": [
            "Ensure automatic boom barriers remain locked at subway portals",
            "Broadcast alternate route advisories via Western Railway FM & Traffic Police Feed"
        ],
        "broadcastSent": True,
        "channels": ["Traffic Police Feed", "Civil Defense"]
    }
]

# =====================================================================
# 8. SEED SIMULATION SCENARIOS DATA
# =====================================================================
SIMULATION_SCENARIOS_DATA: List[Dict[str, Any]] = [
    {
        "id": "scen-baseline",
        "name": "Scenario 1: Moderate Monsoon (35 mm/hr)",
        "title": "Scenario 1: Moderate Monsoon (35 mm/hr)",
        "category": "Routine",
        "rainfallMmHr": 35,
        "rainfallIntensity": 35,
        "rainfallDuration": 60,
        "highTideM": 2.8,
        "drainageBlockagePct": 15,
        "drainageEfficiency": 85,
        "pumpsOnlinePct": 100,
        "estimatedInundationSqKm": 6.2,
        "criticalWards": 1,
        "impactedPopulation": 18000,
        "description": "Standard monsoon showers with operational drainage networks and normal low tide conditions."
    },
    {
        "id": "scen-heavy",
        "name": "Scenario 2: Intense Downpour (70 mm/hr)",
        "title": "Scenario 2: Intense Downpour (70 mm/hr)",
        "category": "Severe Weather",
        "rainfallMmHr": 70,
        "rainfallIntensity": 70,
        "rainfallDuration": 120,
        "highTideM": 3.6,
        "drainageBlockagePct": 30,
        "drainageEfficiency": 70,
        "pumpsOnlinePct": 90,
        "estimatedInundationSqKm": 19.4,
        "criticalWards": 4,
        "impactedPopulation": 85000,
        "description": "Sustained high-intensity precipitation causing localized water accumulation in low-lying railway subways."
    },
    {
        "id": "scen-cloudburst",
        "name": "Scenario 3: Severe Cloudburst + High Tide Lock (115 mm/hr + 4.8m Tide)",
        "title": "Scenario 3: Severe Cloudburst + High Tide Lock (115 mm/hr + 4.8m Tide)",
        "category": "Catastrophic Event",
        "rainfallMmHr": 115,
        "rainfallIntensity": 115,
        "rainfallDuration": 90,
        "highTideM": 4.8,
        "drainageBlockagePct": 45,
        "drainageEfficiency": 55,
        "pumpsOnlinePct": 85,
        "estimatedInundationSqKm": 38.6,
        "criticalWards": 7,
        "impactedPopulation": 240000,
        "description": "Extreme meteorological event. River backflow in Mithi Basin, complete gravity drainage lockout, massive urban inundation."
    },
    {
        "id": "scen-failure",
        "name": "Scenario 4: Major Pump Outage + Heavy Rains (80 mm/hr)",
        "title": "Scenario 4: Major Pump Outage + Heavy Rains (80 mm/hr)",
        "category": "Infrastructure Failure",
        "rainfallMmHr": 80,
        "rainfallIntensity": 80,
        "rainfallDuration": 150,
        "highTideM": 4.1,
        "drainageBlockagePct": 50,
        "drainageEfficiency": 45,
        "pumpsOnlinePct": 50,
        "estimatedInundationSqKm": 31.2,
        "criticalWards": 6,
        "impactedPopulation": 175000,
        "description": "Simulates failure of 50% stormwater de-watering pumps during high tide surge."
    }
]


async def seed_all():
    """Seed the database collections with initial high-fidelity datasets."""
    db = get_database()
    logger.info("Initializing database seed data...")

    collections_to_seed = [
        ("cities", CITIES_DATA),
        ("zones", ZONES_DATA),
        ("sensors", SENSORS_DATA),
        ("infrastructure", INFRASTRUCTURE_DATA),
        ("drainage_nodes", DRAINAGE_NODES_DATA),
        ("roads", ROADS_DATA),
        ("alerts", ALERTS_DATA),
        ("simulation_scenarios", SIMULATION_SCENARIOS_DATA)
    ]

    for col_name, data in collections_to_seed:
        col = db[col_name]
        count = await col.count_documents()
        if count == 0:
            await col.insert_many(data)
            logger.info(f"Seeded {len(data)} documents into '{col_name}'.")
        else:
            logger.debug(f"Collection '{col_name}' already contains {count} documents.")

    logger.info("Database seeding complete.")


if __name__ == "__main__":
    asyncio.run(seed_all())
